### ISSUE TITLE
Make BCO the default format

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nf-prov#13]
I initially kept the legacy format the default, but since we have semantic versions and BCO is likely to become the preferred format, we should make it the default for nf-prov 1.2.

**Comment by stevekm** [comment]
can we output both? I think the legacy version is more readable but the BCO would be useful for publication.

**Comment by bentsherman** [comment]
Yes, see #9

**Comment by bentsherman** [comment]
Closing in favor of #15
