### ISSUE TITLE
add the "script" section to the manifest JSON file

### ISSUE THREAD

**Issue by stevekm** [nextflow-io/nf-prov#24]
can we the get the Nextflow process `script` section added to the output for each Nextflow task? Preferably whatever the contents of the .command.sh file include would be great, thanks. Not sure if its currently available? I am not seeing it in any of my manifest or bco JSON files.

**Comment by bentsherman** [comment]
The BCO format does not have any field for the task script as far as I can tell, but it could be added to the "legacy" format, see #16

**Comment by stevekm** [comment]
that sounds great, I was already saving both formats anyway.

**Comment by stevekm** [comment]
at the risk of scope creep on this issue, I am wondering if this could also include the task .command.log contents too?

**Comment by stevekm** [comment]
maybe worth keeping this in mind too https://github.com/nextflow-io/nf-prov/issues/7 if more potentially large attributes are getting added to the manifest JSON
