### ISSUE TITLE
Support multiple formats in the same run

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nf-prov#9]
Proposed syntax:

```groovy
prov {
  formats {
    legacy {
      file = 'manifest.json'
      overwrite = true
    }
    bco {
      file = 'bco.json'
      overwrite = true
      // could put extra bco-specific fields here, etc
    }
  }
  // ...
}
```

**Comment by simleo** [comment]
For [Workflow Run RO-Crate](https://github.com/nextflow-io/nf-prov/issues/6) the output is actually a directory. It could be output as a zip archive though.

**Comment by bentsherman** [comment]
This is another reason why I want to have separate config for each format, since not every format is guaranteed to output a single file. So an RO-crate for example could have a `directory` setting instead of `file`.
